#Printing version information
hbuana:
        version: 1.0
        github: "https://github.com/wangz1996/hbuana"

#Dat file to ROOT Decoder
DAT-ROOT: 
        on-off: False
        file-list: list_dat.txt
        output-dir: ./

#Pedestal analyse manager
Pedestal:
        on-off: False
        #If work in cosmic mode (hittag==0)
        Cosmic:
                on-off: False
                file-list: "list.txt"
                output-file: "cosmic_pedestal.root"
                usemt: False
        #If work in DAC mode (hittag==1 and skip the calibration channel)
        DAC:
                on-off: False
                file-list: "list.txt"
                output-file: "dac_pedestal.root"

#DAC Calibration Manager
Calibration:
        on-off: False
        #If work in cosmic mode
        Cosmic:
                on-off: False
                file-list: "list.txt"
                ped-file: "pedestal_cosmic.root"
        #If work in DAC mode
        DAC:
                on-off: False
                file-list: "list.txt"
                ped-file: "pedestal_dac.root"
        
